# Generated by Django 4.0.3 on 2022-03-20 14:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviesModel',
            fields=[
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Update At')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('id_movie', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('run_time', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
