# Generated by Django 4.0.3 on 2022-03-22 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moviesmodel',
            name='poster_path',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
