# Generated by Django 4.0.3 on 2022-03-23 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0002_moviesmodel_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='poster_path',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
    ]
