# Generated by Django 4.0.3 on 2022-03-24 13:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies_api', '0003_alter_moviesmodel_poster_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moviesmodel',
            name='owner',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
