# Generated by Django 4.0.3 on 2022-04-01 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0006_alter_moviesmodel_poster_path'),
    ]

    operations = [
        migrations.CreateModel(
            name='GenresModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateField(auto_now_add=True, verbose_name='Create At')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Update At')),
                ('active', models.BooleanField(default=True, verbose_name='Active')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='moviesmodel',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='genres', to='movies_api.genresmodel'),
        ),
    ]
