# Generated by Django 4.0.3 on 2022-04-01 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies_api', '0007_genresmodel_moviesmodel_genres'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genresmodel',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
